services:
  web:
    image: nginx:latest
    ports:
    - "8080:80"
    volumes:
      - ./code:/code
      - ./hosts:/etc/nginx/conf.d
    links:
      - php
  php:
    image: php:8-fpm
    volumes:
      - ./code:/code
      - ./vendor:/vendor
    depends_on:
      - db
    links:
      - db
    env_file:
      - .env
  db:
    image: mysql:8.0
    ports:
      - '6603:3306'
    environment:
      MYSQL_ROOT_PASSWORD: helloworld